services:
  server:
    container_name: server
    depends_on:
      - db
    build: ./server
    ports:
      - '3001:3001'
    env_file:
      - ./server/.env
    volumes:
      - /usr/src/app/node_modules

  socket:
    container_name: socket
    build: ./socket
    ports:
      - '8000:8000'
    env_file:
      - ./socket/.env

  client:
    container_name: client
    build: ./client
    ports:
      - '3000:3000'
    env_file:
      - ./client/.env

  db:
    container_name: db
    image: mysql:8.0.35
    restart: unless-stopped
    ports:
      - '3307:3306'
    env_file:
      - ./docker/db/.env
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/dump:/docker-entrypoint-initdb.d

volumes:
  db-data:
    driver: local
    driver_opts:
      device: ./docker/db/data
  node_modules:
