services:
  server:
    container_name: server
    build: ./docker/Dockerfile.server
    ports:
      - '3001:3001'
    env_file:
      - ./server/.env

  socket:
    container_name: socket
    build: ./docker/Dockerfile.socket
    ports:
      - '8000:8000'
    env_file:
      - ./socket/.env

  client:
    container_name: client
    build: ./docker/Dockerfile.client
    ports:
      - '3000:3000'
    env_file:
      - ./client/.env

  database:
    container_name: database
    build: ./docker/Dockerfile.database
    ports:
      - '3306:3306'
    env_file:
      - ./docker/db/.env
    volumes:
      - ./docker/db/data:/var/lib/mysql
volumes:
  db-data:
    driver: local
    driver_opts:
      device: ./docker/db/data

