version: '3.8'
services:
  server:
    container_name: server
    build: ./server
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - APP_URL=${APP_URL}

